- hosts: all
  name: Autoconverted job legacy-periodic-tempest-dsvm-networking-sfc from old job
    periodic-tempest-dsvm-networking-sfc-ubuntu-xenial
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin networking-sfc git://git.openstack.org/openstack/networking-sfc

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_NEUTRON=1
          # Make sure tempest is installed, but run it out of the post_test_hooks.sh
          # script from the networking-sfc repository.
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_NOTESTS=1

          export BRANCH_OVERRIDE=master
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi
          # Because we are testing a non standard project, add
          # our project repository. This makes zuul do the right
          # reference magic for testing changes.
          export PROJECTS="openstack/networking-sfc $PROJECTS"

          # Keep localrc to be able to set some vars in pre_test_hook
          export KEEP_LOCALRC=1

          function pre_test_hook {
              if [ -f $BASE/new/networking-sfc/devstack/pre_test_hook.sh ] ; then
                  . $BASE/new/networking-sfc/devstack/pre_test_hook.sh
              fi
          }
          export -f pre_test_hook

          function gate_hook {
              if [ -f $BASE/new/networking-sfc/networking_sfc/tests/contrib/gate_hook.sh ] ; then
                  bash -xe $BASE/new/networking-sfc/networking_sfc/tests/contrib/gate_hook.sh dsvm-networking-sfc
              fi
          }
          export -f gate_hook

          function post_test_hook {
              if [ -f $BASE/new/networking-sfc/devstack/post_test_hook.sh ] ; then
                  . $BASE/new/networking-sfc/devstack/post_test_hook.sh
              fi
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
